### ISSUE TITLE
Apt provider should only run if package isnt installed

### ISSUE THREAD

**Issue by Jc2k** [yaybu/yaybu#10]
Check to see if package is installed before trying to install it

**Comment by tomwardill** [comment]
Taken from Fab:

{{{
def install_package(package):
    with settings(hide('warnings', 'stderr'), warn_only= True):
        result = sudo('dpkg-query --show %s' % package)
    if result.failed is False:
        warn('%s is already installed' % package)
    else:
        sudo('apt-get -y --no-upgrade install %s' % package)
}}}

**Comment by tomwardill** [comment]
Closed by 7611e94317d78caf637c8304a4d6c25958347be0. Search if a package is already installed and don&#39;t attempt to install it if it is.
