### ISSUE TITLE
Search path is forgotten sometimes

### ISSUE THREAD

**Issue by winjer** [yaybu/yaybu#127]
Create a Yaybufile like:

```
yaybu:
    searchpath:
        - .

include "foo.yay"

x: y

include "quux.yay"
```

touch foo.yay and quux.yay.

On running yaybu up, foo.yay is not found. Removing either of the x:y or the later include allows it to be found.

**Comment by Jc2k** [comment]
When there are 2 adjacent include nodes the resolver will eagerly expand it's predecessor. That means that the oldest include node (in this case foo.yay) gets parsed before quux.yay. The search path handling expects includes to be handled in that way. However dicts didn't chain to predecessors, so the search path code gets invoked twice before ever reaching the `yaybu.searchpath` expression.
