### ISSUE TITLE
Whitespaces in templates can mess remotely executed commands

### ISSUE THREAD

**Issue by jose-lpa** [yaybu/yaybu#139]
Hello,

We have noticed today that a little neglect when writing your Yaybu configuration can lead to failures when actually deploying a project.

Our case was that we unintentionally added several whitespaces after using a templates variable when defining some file properties. Specifically, we were trying to perform a `chown` over a certain file, and to define the owner and group for that file we used template vars, adding by mistake some whitespaces after the `{{ file_group }}` declaration. That provoked Yaybu to try to perform this:

`chown file-group_________ FILE_TO_CHANGE`

instead of this:

`chown file-group`

You can see the underscores after the first `file-group` as a whitespaces, to understand better what happened.

I attach a screenshot of my shell with the Yaybu deployment error and a diff, so you can probably see the problem in a better way.

![screen shot 2014-05-20 at 11 57 03](https://cloud.githubusercontent.com/assets/2226098/3027026/e2c0a6aa-e01d-11e3-821e-3a7f2b4a1e55.png)

Do you think this is an error that can be avoided in the future by Yaybu? Of course the whitespaces should not be there, but maybe it is possible to let Yaybu be more "tolerant" with such (apparently harmless) typos.

Thank you very much for your time!

**Comment by Jc2k** [comment]
Thanks for the bug report! I'm going to be overhauling that bit of code soon so i'll make sure to add some handling for this.

**Comment by jose-lpa** [comment]
Great. Thank you! :)

**Comment by winjer** [comment]
I suspect this is my problem. Strings that aren't quoted should probably be stripped in the lexer or the parser, wherever we know it's quoted.
