### ISSUE TITLE
Yaybu remote

### ISSUE THREAD

**Issue by winjer** [yaybu/yaybu#16]
Invoked like this:

 yaybu <hostname> <filename>

So two args = remote, one arg = local

Will refuse to invoke when run as root with only one argument.

The user will need to be able to invoke yaybu-remote using sudo.  The invocation on the remote side will need to use a trampoline like:

 yaybu-remote --trampoline

This inspects the environment and take ssh agent details to pass as parameters:

 sudo yaybu-remote --ssh-auth-sock /tmp/foo/bar

The process then has root privileges and a secure channel to the local process.

**Comment by Jc2k** [comment]
This works now, but depends on /etc/sudoers foo
