### ISSUE TITLE
RESTful on the wire protocol

### ISSUE THREAD

**Issue by winjer** [yaybu/yaybu#17]
We need to support the following methods:

 GET
 POST

For a url of the format python://foo.bar/baz we will request:

 GET /baz

The server will respond with 200, 404 or 401 or other codes as appropriate. The response headers will be exactly as for HTTP.

POST similarly will work exactly as per HTTP spec.

**Comment by Jc2k** [comment]
Merged in to master - 'yaybu --host victim recipe.yay' has a SSH tunneled HTTP link between the invoking yaybu/terminal and the remote actor performing system modifications.
