### ISSUE TITLE
how can we avoid calling dpkg-reconfigure every time?

### ISSUE THREAD

**Issue by winjer** [yaybu/yaybu#21]
Every run of a command like this, will do this:

/-------------------------- Execute[reconfigure-exim] --------------------------
| /usr/sbin/dpkg-reconfigure -f noninteractive exim4-config
-------------------------------------------------------------------------------

How do we not do that every time?

**Comment by Jc2k** [comment]
Invalid - its only happening because our cookbook doesn't have the signals it should.
