### ISSUE TITLE
Cope with stale state

### ISSUE THREAD

**Issue by winjer** [yaybu/yaybu#73]
The state file may not represent the real state of servers.

Before any operation on a cluster, verify the state file against reality and then provide recovery features.

Possible cases:
- a node has failed during creation and yaybu terminated (indicated by a half-written transaction in the state file)
- a server has been destroyed or is uncontactable, even though it is referenced in the state file

**Comment by Jc2k** [comment]
The new compute code copes with these sorts of failures.
