### ISSUE TITLE
Add Human or Prompt resource

### ISSUE THREAD

**Issue by Jc2k** [yaybu/yaybu#8]
This resource type is for scenarios where yaybu is used like a system level Buildout. There maybe actions where we still need administrators to perform manual steps. The Prompt resource and provider simply halt execution of yaybu until admin hits the continue button (enter :P)

**Comment by tomwardill** [comment]
Closed by f1e1b6f205ad1c657dfad33ca152c291e3bde429. Prompt resource and provider added
